### ISSUE TITLE
Substantial delay in Livestreaming videos.

### ISSUE THREAD

**Issue by crjacinro** [Firekast-io/firekast-demo-android#4]
When I am live streaming in Android, a substantial delay is encountered (around 20 - 25 seconds). This is really not ideal when live streaming real time scenarios (such as user location in real time). 

I am using firekast SDK version 1.2.5 and displaying the live video in Firekast IO console. 

<img width="1024" alt="Screen Shot 2019-03-09 at 7 52 34 PM" src="https://user-images.githubusercontent.com/28602346/54071281-4c616880-42a5-11e9-9122-0faacbd5c500.png">

**Comment by francoisrouault** [comment]
Hi crjacinro, 
Indeed firekast currently only supports live streaming and not video conferencing (like skype or facetime) yet although its in our roadmap. Live streaming uses a different technology than video conferencing. It can handle hundred of thousands viewers on a single stream and is between ten to a hundred times cheaper. In order to maximise the experience on mobiles, we distribute live stream using the adaptative format, i.e the streams quality is adjusted to your viewers available bandwidth and this requires the introduction of a lag. We however work intensively to reduce the delay and it should be able to optimize it in the coming months.
Could you please [contact us](https://firekast.zendesk.com/hc/en-gb/requests/new) to explain your use case and what delay would be acceptable for it?
Kind regards

**Comment by crjacinro** [comment]
Example of a real time use case is to livestream current user's location, especially inside a building. So any delays will result to inaccurate experience.  Are there any plans to minimize delay in the upcoming versions of the SDK sooner?

**Comment by francoisrouault** [comment]
Yes, but bear in mind that in the short term the delay would still be around 10 seconds using our live streaming solution. If your usecase requires video conferencing with zero delay, we unfortunately can’t provide a release date yet as our main focus is live streaming. If it is not the case, the best to move forward is to schedule a quick chat with our customer success team members. Could you please send a quick description of your usecase to support@firekast.io or fill a request on this [page](https://firekast.zendesk.com/hc/en-gb/requests/new).

**Comment by crjacinro** [comment]
Ok looking forward for the 10 second window for now.
